version: "3.8"

services:
  web:
    build: .
    command: python3 app.py
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    depends_on: 
        - db
  db:
    image: postgres:13-alpine
    container_name: flask_library_docker
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=flask_library
        - POSTGRES_HOST=flask_host
volumes:
  pgdata: 