version: "3.8"

services:
  web:
    build: .
    command: python3 app.py
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    depends_on: 
        - db
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=flask_library
        - POSTGRES_HOST=postgres
volumes:
  pgdata: 